### ISSUE TITLE
Create Contribution Guidelines

### ISSUE THREAD

**Issue by jawadsh123** [DanishShah/DeepDiagnosis#1]
A barebones and simple guideline will do for now.
Some nice resources --
[Setting Guidelines for Repository Contributors](https://help.github.com/articles/setting-guidelines-for-repository-contributors/)
[Good CONTRIBUTING.md template](https://gist.github.com/PurpleBooth/b24679402957c63ec426)

**Comment by sameerkumar18** [comment]
Working on it.

**Comment by sameerkumar18** [comment]
Please review #2
